[[main]]
  identifier = "about"
  name = "关于我"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "归档"
  url = "archive"
  weight = 10

[[main]]
  identifier = "posts"
  name = "博客"
  url = "posts"
  weight = 20

